version: 2.1
jobs:
  build:
    docker: 
      - image: emscripten/emsdk
    steps:
      - checkout
      - run:
          name: "Build"
          command: source circleci-build-web.sh
      - persist_to_workspace:
          root: builds/
          paths: web
  deploy:
    docker:
      - image: node
    steps:
      - checkout
      - attach_workspace:
          at: builds
      - run:
          name: Install gh-pages
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@circleci.com"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "e6:4d:ef:39:6e:c8:0d:ba:4a:fd:b8:98:87:a6:27:ca"
      - run:
          name: Deploy
          command: gh-pages --dist builds/web
workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build

